-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Feb 09, 2020 at 02:45 PM
-- Server version: 5.7.19
-- PHP Version: 5.6.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `shop`
--

-- --------------------------------------------------------

--
-- Table structure for table `cart`
--

DROP TABLE IF EXISTS `cart`;
CREATE TABLE IF NOT EXISTS `cart` (
  `cartId` int(200) NOT NULL AUTO_INCREMENT,
  `productIdConnect` int(200) NOT NULL,
  `userIdConnect` int(200) NOT NULL,
  `orderQuantity` int(200) NOT NULL,
  `totalPrice` int(200) UNSIGNED NOT NULL,
  PRIMARY KEY (`cartId`)
) ENGINE=MyISAM AUTO_INCREMENT=152 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `cart`
--

INSERT INTO `cart` (`cartId`, `productIdConnect`, `userIdConnect`, `orderQuantity`, `totalPrice`) VALUES
(149, 162, 6, 1, 3122),
(148, 163, 6, 2, 24622);

-- --------------------------------------------------------

--
-- Table structure for table `comment`
--

DROP TABLE IF EXISTS `comment`;
CREATE TABLE IF NOT EXISTS `comment` (
  `commentId` int(200) UNSIGNED NOT NULL AUTO_INCREMENT,
  `costumerIdConnect` int(200) NOT NULL,
  `productIdConnect` int(200) NOT NULL,
  `commentDescription` text NOT NULL,
  `commentDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`commentId`)
) ENGINE=MyISAM AUTO_INCREMENT=35 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `comment`
--

INSERT INTO `comment` (`commentId`, `costumerIdConnect`, `productIdConnect`, `commentDescription`, `commentDate`) VALUES
(2, 3, 83, 'Josemacayanan', '2018-04-14 18:37:32'),
(3, 3, 162, 'Hi', '2018-04-14 19:00:59'),
(4, 3, 162, 'Nice. Buy this product worth of Money!!', '2018-04-14 19:01:42'),
(5, 2, 162, 'Thanks Admin for feedback', '2018-04-14 19:02:28'),
(6, 2, 162, 'Thanks Admin for feedback', '2018-04-14 19:02:56'),
(7, 2, 162, 'Okay', '2018-04-14 19:03:33'),
(8, 2, 162, 'tHANKS', '2018-04-14 19:06:42'),
(9, 3, 78, 'Nice camera', '2018-04-15 03:42:13'),
(10, 3, 78, 'Thank You', '2018-04-15 04:12:37'),
(11, 3, 162, 'Okay NO prob', '2018-04-15 04:16:06'),
(12, 3, 162, 'Hello', '2018-04-16 10:10:27'),
(13, 3, 78, 'Fafa', '2018-04-16 10:35:43'),
(20, 2, 162, 'Hi', '2018-04-18 03:30:13'),
(21, 2, 162, 'Js', '2018-04-18 03:30:58'),
(22, 5, 162, 'Nice!!', '2018-04-18 03:55:24'),
(23, 3, 162, 'Its me', '2018-04-18 05:52:54'),
(24, 3, 137, 'Nice App', '2018-04-18 06:21:01'),
(25, 2, 163, 'NIce', '2018-04-18 06:25:42'),
(26, 3, 163, 'Yess?', '2018-04-20 04:11:35'),
(27, 3, 163, '', '2018-04-20 04:11:35'),
(28, 3, 163, 'jose', '2018-11-23 13:42:38'),
(29, 3, 163, 'jose', '2018-11-23 13:42:38'),
(30, 3, 163, 'j', '2018-11-23 13:42:47'),
(31, 3, 163, 'hi', '2019-03-21 23:16:21'),
(32, 3, 163, 'm', '2019-03-21 23:16:27'),
(33, 3, 163, 'sample text', '2019-03-22 09:58:32'),
(34, 3, 160, 'q', '2019-03-22 10:36:12');

-- --------------------------------------------------------

--
-- Table structure for table `costumer`
--

DROP TABLE IF EXISTS `costumer`;
CREATE TABLE IF NOT EXISTS `costumer` (
  `costumerID` int(255) NOT NULL AUTO_INCREMENT,
  `username` varchar(25) NOT NULL,
  `password` text NOT NULL,
  `birthday` date NOT NULL,
  `firstname` text NOT NULL,
  `lastname` text NOT NULL,
  `address` text NOT NULL,
  `phone` int(200) NOT NULL,
  PRIMARY KEY (`costumerID`),
  UNIQUE KEY `username` (`username`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `costumer`
--

INSERT INTO `costumer` (`costumerID`, `username`, `password`, `birthday`, `firstname`, `lastname`, `address`, `phone`) VALUES
(3, 'admin', 'admin1', '1999-02-20', 'admin', 'admin', 'admin', 1234567890),
(2, 'Jose', 'qwe ', '2018-12-31', 'Joselin ', 'Macayanan ', 'Maria Aurora ', 121121),
(5, 'jeff', 'qwe ', '0012-12-12', 'Jefferson ', 'Cueva ', 'Caranglan ', 9278),
(6, 'jasmin', 'jasmin ', '2019-03-05', 'Jasmin ', 'Lazaro ', 'Cuyapo ', 912121212);

-- --------------------------------------------------------

--
-- Table structure for table `product`
--

DROP TABLE IF EXISTS `product`;
CREATE TABLE IF NOT EXISTS `product` (
  `productId` int(11) NOT NULL AUTO_INCREMENT,
  `productName` text NOT NULL,
  `category` text NOT NULL,
  `price` int(255) UNSIGNED NOT NULL,
  `quantity` int(255) UNSIGNED NOT NULL,
  `productImage0` text NOT NULL,
  `productImage1` text NOT NULL,
  `productImage2` text NOT NULL,
  `productImage3` text NOT NULL,
  `released` date NOT NULL,
  `brand` text NOT NULL,
  `model` text NOT NULL,
  `productDescription` text,
  PRIMARY KEY (`productId`)
) ENGINE=MyISAM AUTO_INCREMENT=167 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `product`
--

INSERT INTO `product` (`productId`, `productName`, `category`, `price`, `quantity`, `productImage0`, `productImage1`, `productImage2`, `productImage3`, `released`, `brand`, `model`, `productDescription`) VALUES
(103, 'Honor 7X - 18:9 screen ratio, 5.93 ', 'Mobile Phone', 12111, 10, 'image/7x1.PNG ', ' image/7x2.PNG ', ' image/7x3.PNG ', ' image/7x4.PNG ', '2018-05-03', 'Honor', ' 7X ', ' Edge-to-edge all-screen design. With a high screen-to-body ratio and 2160 x 1080 FHD  resolution, the Honor Full View display on the Honor 7X brings you an astonishing, immersive visual experience.Take the lead in games. The Honor 7xâ€™s 18: 9 screen provides more real estate than a traditional 16: 9 screen, giving you a wider view than other gamers.Never fall behind in catching up with friends while watching videos. The one-key screen split function offers an even faster multi-management experience.The Classic metal design of the Honor 7X is a delight to hold, with its perfectly rounded edge. The 2.5D glass face flows seamlessly into the aluminum chassis.The dual-lens 16MP   2MP rear Camera captures lifeâ€™s magical moments in the highest definition, empowering your inner photographer'),
(78, 'King Gear Digital Camera ', 'Camera', 4800, 97, 'image/king_gear - Copy (2).PNG ', ' image/king_gear - Copy (3).PNG ', ' image/king_gear - Copy.PNG ', ' image/king_gear.PNG ', '2018-04-11', 'King Gear Camera', ' Gear Digital 108 ', ' > Slightly used camera> High performance Optical Viewfinder helps facilitate quick and accurate focusing by firmliy framing and capturing the subject ate hand.> 3.0â€ LCD screen for easy viewing and photo editing.> Includes lenses and charger.'),
(80, 'Aberg ', 'Camera', 1212, 14, 'image/aberg1.jpg ', 'image/aberg2.jpg ', 'image/aberg3.jpg ', 'image/aberg4.jpg ', '2018-04-11', 'Aberg', 'aberg ', 'Newest software is updated! The applicable uses for this Digital Camera: digital still images, Web Cam, Play Back, Video record, voice reord and so on.2.7\" TFT LCD display show you vivid video,550mAh Lithium Ion (Li-Ion) rechargeable battery can support camera works more than 60 minutes.21 mega pixels resolution for good capture, HD 720P resolution for recording, create your HD masterpiece! Support External-Memory MAX 64G SD card. ( Not included )Anti-shake, Face Detect, Smile Capture, Continue Shot, Self Timer, 8X Digital Zoom, PhoTags Express Software for Photo Editing, Printing, and Sharing with E-mails, etc.Satisfaction Guaranteed, you\'ll love this Video camera Digital or you\'ll get your money back! '),
(81, 'Sony W800/S 20.1 MP Digital Camera (Silver) ', 'Camera', 2000, 12, 'image/sony_camera.jpg ', ' image/sony_camera1.jpg ', ' image/sony_camera2.jpg ', ' image/sony_camera3.jpg ', '2018-04-11', 'Sony', ' Slr 12 ', ' MP Super HAD CCD sensor for beautifully detailed images.Sony Lens w/ 5x Optical Zoom.Reduced blur with SteadyShot Image stabilizationCapture your videos in 720p HD Movie modeSimplify camera menu with Easy Mode'),
(82, 'Canon PowerShot ELPH 180 Digital Camera ', 'Camera', 1233, 12, 'image/canon1.jpg ', 'image/canon2.jpg ', 'image/canon3.jpg ', 'image/canon4.jpg ', '2018-04-11', 'Canon', 'ELPH ', ' 8x Optical Zoom with Optical Image Stabilizer helps you capture images with flexibility and ease20.0 Megapixel CCD sensor combines with the DIGIC 4  Image Processor to help deliver stunning image quality720p HD video capabilities.Focusing Range:Normal: 2.0 in. - infinity (W), 4.3 ft. (1.3m) - infinity (T)Smart AUTO intelligently selects the proper settings based on predefined shooting situationsDigital IS helps reduce the effect of camera shake and subject movementScene Modes such as Fisheye Effect, Toy Camera Effect and Monochrome provide creative freedom to capture your photos '),
(83, 'Canon Cameras US 1084C001 Canon PowerShot ELPH 190  ', 'Camera ', 3000, 28, 'image/canon_us1.jpg ', 'image/canon_us2.jpg ', 'image/canon_us3.jpg ', 'image/canon_us4.jpg ', '2018-04-11', 'Canon', 'ELPH ', 'Video digital camcorder: 2.7 inch TFT LCD(16:9),available with 270 degree rotation, fill-in infrared LED light(Please note that the camcorder doesn\'t come with a external microphone and its design can\'t support external microphone.)CMOS image sensor: Max to 24 Megapixels(1920X1080P),16X Digital zoom camera, Storage media SD/MMC card(4GB to 32GB),Supports standard tripod (please note that the tripod and SD card are not included) .Long lasting battery: 1*np-40,3.7v 1200 mah li-ion battery (package included),Original rechargeable lithium battery, If it full charged can be sustainable 2.5-3.5 hours,Swith off power before replacing battery.Camcorder features: Hd camera camcorder, auto power-off, face capture,anti-shake, with internal microphone, speaker,LED light, USB port 2.0,TV output PAL/NTSC,Multi-Languages, Operating system requirements Windows 7/2002/XP/Vista.Lightweight and small camcorder: Easy to carry and store, High-class material and advanced technology, record high-quality image, perfect to be a gift and record your special lovely moments, give you a beautiful happy memory in your life.   '),
(84, 'Digital Camera Camcorders Kimire HD ', 'Camera', 4111, 26, 'image/kimire1.jpg ', 'image/kimire2.jpg ', 'image/kimire3.jpg ', 'image/kimire4.jpg ', '2018-04-11', 'Kimire', 'Camcorders ', 'Video digital camcorder: 2.7 inch TFT LCD(16:9),available with 270 degree rotation, fill-in infrared LED light(Please note that the camcorder doesn\'t come with a external microphone and its design can\'t support external microphone.)CMOS image sensor: Max to 24 Megapixels(1920X1080P),16X Digital zoom camera, Storage media SD/MMC card(4GB to 32GB),Supports standard tripod (please note that the tripod and SD card are not included) .Long lasting battery: 1*np-40,3.7v 1200 mah li-ion battery (package included),Original rechargeable lithium battery, If it full charged can be sustainable 2.5-3.5 hours,Swith off power before replacing battery.Camcorder features: Hd camera camcorder, auto power-off, face capture,anti-shake, with internal microphone, speaker,LED light, USB port 2.0,TV output PAL/NTSC,Multi-Languages, Operating system requirements Windows 7/2002/XP/Vista.Lightweight and small camcorder: Easy to carry and store, High-class material and advanced technology, record high-quality image, perfect to be a gift and record your special lovely moments, give you a beautiful happy memory in your life.  '),
(85, 'Camcorder Video Camera Full HD ', 'Camera', 1231, 34, 'image/lnsse1.jpg ', 'image/lnsse2.jpg ', 'image/lnsse3.jpg ', 'image/lnsse4.jpg ', '2018-04-11', 'LNNSE', 'LNSSE12CS ', ' Full HD 1080p 24.0MP Camcorder: This camera camcorder supports 1080p video resolution and 24.0 MP picture resolutions. You can capture premium photos and videos with this camera. The camcorder is light and small which makes it convenient to carry with. It can easily fit in your handbag. This camcorder is also very easy to operate. There is a remote controller that comes with the package, which can help you to take group photos.Night Vision Function: The camera supports Night Vision Function. There are two pieces of IR lights at the top of the camera lens and its working distance can reach up to ft 3m which allows you to take black-and-white photos and videos event in the dark night. Therefore, it is a great choice for those who like to find enthusiasts or ghost hunting.Pause Function: This camcorder is a good choice for vlogging. You can take advantage of pause function, with which you can continue the recording in the same file without restarting a new one. You can transfer your photos or video to your computer through USB cord. Besides, you can connect your camera to TV and play your video trough the AV cable which is coming with the package.Multi-Function: This camera supports smile capture function. After you have enabled it, it will make a shot automatically when a smile on your face has been detected by the camera. This camcorder is also designed with multi functions, including anti-shake, 18X digital zoom and beauty face and so on, which can share a quality for your captures. It is highly recommended for family functions and filmmakers.Warranty: One year warranty will be provided by LINNSE and customer service will be available within 24 hours. A 1000 mAh Li-ion battery will come as standard with this package. This camcorder can support up to 32GB SD card, so you donâ€™t have to worry about its storage being full or battery running low warning. SD card needs to be purchased separately. '),
(86, 'Canon EOS Rebel T6 Digital SLR Camera Kit ', 'Camera', 2331, 11, 'image/eos1.jpg ', 'image/eos2.jpg ', 'image/eos3.jpg ', 'image/eos4.jpg ', '2018-04-11', 'Canon', 'Canon ', ' ImagingLens Mount: Canon EF, EF-SPixels: Actual: 18.7 M,Effective: 18 MegapixelAspect Ratio: 3:2Sensor Type / Size: CMOS, 22.3 x 14.9 mmFile Formats: Still Images: JPEG, RAWMovies: MOV, MPEG-4 AVC/H.264Audio: :Linear PCMMemory Card Type: SD ,SDHC, SDXCViewfinder/DisplayViewfinder Type: PentamirrorViewfinder Eye Point: 21.00 mmViewfinder Coverage: 95%Viewfinder Magnification: Approx. 0.8xDiopter Adjustment: -2.5 to  0.5 mDisplay Screen: 3\" Rear Screen LCD (920,000) Screen Coverage: 100%Diagonal Angle of View: 170.0Â°PerformanceStart-up Time: 0.1 secondsShutter Lag: 0.12 secondsSelf Timer: 10 Seconds, 2 SecondsConnectivity: 2.5mm Sub-mini (2-Ring), HDMI C (Mini), Mini-USB, USB 2.0Wi-Fi Capable: YesPhysicalDimensions (WxHxD) :5.1 x 4.0 x 3.1\" / 129.0 x 101.3 x 77.6 mmWeight:17.1 oz / 485 g CIPAPackage Weight: 3.2 lbBox Dimensions (LxWxH) : 8.8 x 6.6 x 5.4\"Kit LensFocal Length: 18 - 55mmAperture: Maximum: f/3.5 - 5.6Minimum: : f/22 - 38Dimensions (DxL) : Approx. 2.70 x 2.80\" (68.5 x 71.1 mm) Weight: 7.09 oz (201 g) '),
(87, 'Fujifilm FinePix XP80  ', 'Camera', 2111, 11, 'image/fujifilm1.jpg ', ' image/fujifilm2.jpg ', ' image/fujifilm3.jpg ', ' image/fujifilm4.jpg ', '2018-04-11', 'Fujifilm', ' FinePixXp80 ', ' Product Dimensions5.5 x 5.5 x 2 inchesItem Weight1 poundsShipping Weight15.2 ounces (View shipping rates and policies)ASINB00S4KXH3KItem model numberFinePix XP80 Graphite BlackBatteries1 Lithium ion batteries required. (included)4 Way Proof - Waterproof 50 ft / 15m, Freeze proof 14 Degree F / -10 DegreeC, Shockproof 5.8 ft / 1.75m and Dustproof.16.2 megapixel backlit CMOS sensor delivershigh-quality images in low light.Continuous shooting mode is capable of capturing up to 10.0fps (maximumrecording of 10 images at full resolution).Full HD Movies with one-touch movie button.Connect to your smartphone or tablet for extra enjoyment for Remote Shooting and Wireless Image Transfer.'),
(88, 'Sony DSCW830 20.1 MP Digital Camera with 2.7-Inch LCD (Silver) ', 'Camera', 1211, 12, 'image/dsc1.jpg ', ' image/dsc2.jpg ', ' image/dsc3.jpg ', ' image/dsc4.jpg ', '2018-04-11', 'Sony', ' sony DSCW830 ', ' 20.1 Megapixel(effective) Plus 8x Zoom and number of pixels (Gross)is approx. 20.4 megapixelsOptical Steady Shot image Stabilization with 2-way Active Mode720p MP4 HD Movie Mode ; This product is compatible with Final Cut Pro X and iMovie.Panorama Shooting: 360 Sweep Panorama; Minimum Illumination: Auto: 22.0 lux Shutter Speed 1/30Picture Effect: Still images: Toy camera, Pop Color, Partial Color, Soft High-key, Panoramas: Pop Color, Partial Color, Soft High-key, Movies: Toy camera, Pop Color, Partial Color, Soft High-keyCamera Type:Compact zoom digital cameraImaging Sensor:1/2.3\" Super HAD CCD SensorProcessor:BIONZPixel Gross:20.5MPEffective Picture Resolution:20.1MPColor Filter System:RGB primary color mosaic filtersMedia Type:Memory Stick Duo; Memory Stick PRO Duo; Memory Stick PRO Duo(High Speed); Memory Stick PROHG Duo; Memory Stick Micro*6 ; Memory Stick Micro (Mark2)*6 ; SD/SDHC/SDXC Memory Card; microSD Memory Card*6; microSDHC Memory Card*6; Memory Stick XC-HG Duo; microSDXC Memory Card*6Still Image Mode:JPEGStill Image Max Effective Resolution:Approx. 20.1 MegapixelsStill Image Size 16:9:15M (5,152 x 2,896)/ 2M(1,920 x 1,080)Still Image Size 4:3:20M (5,152 x 3,864)/ 10M(3,648 x 2,736) / 5M(2,592 x 1,944) /VGAPanorama Still Image Size:360 (11,520Ã—1,080) / Wide(7,152 x 1,080 / 4,912 x 1,920) / Standard (4,912 x 1,080 / 3,424 x 1,920)Video Format:MP4 (AVC/H.264)Video Mode:MP4:9M Fine(1,280Ã—720/30fps)/6M STD(1,280Ã—720/30fps)/3M VGA(640Ã—480/30fps)Audio Format:MP3'),
(89, 'Canon PowerShot ELPH 180  ', 'Camera', 1121, 31, 'image/elph1.jpg ', ' image/elph2.jpg ', ' image/elph3.jpg ', ' image/elph4.jpg ', '2018-04-12', 'Canon', ' elph180 ', ' 8x Optical Zoom with Optical Image Stabilizer helps you capture images with flexibility and ease20.0 Megapixel CCD sensor combines with the DIGIC 4  Image Processor to help deliver stunning image quality720p HD video capabilities. Product Dimensions(W x H x D):3.75 x 2.14 x 0.87 inches/95.2 x 54.3 x 22.1 mmSmart AUTO intelligently selects the proper settings based on predefined shooting situationsDigital IS helps reduce the effect of camera shake and subject movement. Scene Modes such as Fisheye Effect, Toy Camera Effect and Monochrome provide creative freedom to capture your photosProduct Dimensions3.8 x 0.9 x 2.1 inchesItem Weight4.5 ouncesShipping Weight9.6 ounces (View shipping rates and policies)ASINB019UDHT6UItem model number1096C001Batteries1 Lithium ion batteries required. (included)'),
(90, '2018 Newest HP Premium 15.6 Laptop ', 'Laptop', 14000, 33, 'image/p_hp1.jpg ', ' image/p_hp2.jpg ', ' image/p_hp3.jpg ', ' image/p_hp4.jpg ', '2018-04-17', 'Hp', 'Hp Laptop AND12 ', ' AMD Dual-Core A6-9220 Processor 2.50GHz, up to 2.90 GHz. Integrated AMD Radeon R4 Graphics4 GB DDR4L SDRAM Memory, 500 GB 5400 rpm Hard Drive, DVD-RW Burner15.6\" diagonal HD (1366 x 768) SVA BrightView WLED-backlit display; Webcam, DTS Studio Sound1 HDMI, 2 USB 3.1, 1 USB 2.0, 1 Headphone/microphone combo jack, 1 RJ-45, 1 multi-format SD media card readerWindows 10 Home, 3-cell Lithium-ion up to 6.25 h battery life, weighs 4.52 lbs. and measures 0.9\" thin, Color: Jet BlackScreen Size15.6 inchesMax Screen Resolution1366 x 768Processor2.5 GHz Athlon 2650eRAM4 GB SDRAMHard Drive500 GB mechanical_hard_driveGraphics CoprocessorAMD Radeon R4Chipset BrandamdCard DescriptionintegratedWireless Type802.11 B/G, 802.11 A/C, 802.11bgn, 802.11BAverage Battery Life (in hours)6.25 hours'),
(91, 'ASUS L402WA-EH21 Thin and Light 14â€ HD Laptop   ', 'laptop ', 13000, 11, 'image/ausu_e1.jpg ', 'image/ausu_e2.jpg ', 'image/ausu_e3.jpg ', 'image/ausu_e4.jpg ', '2018-04-26', 'Asus', 'L402WA ', ' Efficient AMD E2-6110 1.5GHz Processor with integrated Radeon R2 graphics for crisp and clear visuals1-year Microsoft Office 365 Personal subscription includedWindows 10 S pre-installed. Windows 10 S is the new standard in portable cloud-based operating systems. Windows 10 S is the 100% app based version of Windows 10 where Store apps are verified and designed for superior performance and security32GB eMMC Flash Storage and 4GB DDR3 RAMOptional free upgrade to Windows 10 Pro through the Microsoft StoreScreen Size14 inchesMax Screen Resolution1366x768 pixelsProcessor1.5 GHzRAM4 GB DDR3Hard DriveFlash Memory Solid StateGraphics CoprocessorAMD Radeon R2Chipset BrandintelCard DescriptionIntegratedWireless Type802.11nNumber of USB 2.0 Ports1Number of USB 3.0 Ports2  '),
(92, 'Dell Latitude E7240 Ultrabook PC ', 'Laptop', 50000, 11, 'image/dell_L1.jpg ', ' image/dell_L2.jpg ', ' image/dell_L3.jpg ', ' image/dell_L4.jpg ', '2018-04-20', 'Dell', 'Latitude E7240 ', ' This Certified Refurbishd product is tested and certified to look and work like new. The refurbishing process includes functionality testing, basic cleaning, inspection, and repackaging. The product ships with all relevant accessories, a minimum 90-day warrantty, and may arrive in a generic box. Only select sellers who maintain a high performance bar may offer Certified Refurbishd products on Amazon.comIntel Core i5-4300U 1.9GHz Processor.8GB DDR3 - 128GB Solid State Drive.Windows 10 Professional (64-Bit).12.5 inch HD (1366x768) Anti-Glare LED-backlit Display.Screen Size12.5 inchesScreen Resolution1366x768Max Screen Resolution1366 x 768Processor1.9 GHz Intel Core i5RAM8 GB SDRAM DDR3Hard Drive128 GB SSDChipset BrandintelWireless Type802.11bgn'),
(93, 'Lenovo IdeaPad 320 15.6-inch HD Anti-Glare ', 'Laptop', 30112, 21, 'image/lenovo_I1.jpg ', ' image/lenovo_I2.jpg ', ' image/lenovo_I3.jpg ', ' image/lenovo_I4.jpg ', '2018-04-24', 'Lenovo', 'IdeaPad 320 ', ' 15.6\" LED Backlit HD Anti-Glare Display (1366x768) Display, Intel HD Graphics 500, DVD-RWIntel Dual Core Celeron N3350 1.10GHz Processor (Turbo boost up to 2.40GHz, 2M Cache)4GB DDR4 SDRAM, 1TB 5400 RPM HDD, HD webcam, 4-in-1 Media card reader802.11ac WLAN, Bluetooth, HDMI, 1x USB 2.0, 1 x USB 3.0, 1 x headphone/microphone jack, Up to 4 hours and 30 minutes battery lifeWindows 10 64-bit Home, Dimensions: 14.88\" x 10.24\" x 0.90\", Weight: 4.84 lbs, Color: BlackScreen Size15.6 inchesScreen Resolution1366x768Max Screen Resolution1366 x 768Processor1.1 GHz Intel CeleronRAM4 GB SDRAMHard Drive1 TB HDD 5400 rpmGraphics CoprocessorIntel HD Graphics 500Chipset BrandintelCard DescriptionintegratedWireless Type802.11A'),
(94, 'ASUS VivoBook F510UA FHD Laptop ', 'Laptop', 60121, 12, 'image/asus_f1.jpg ', ' image/asus_f2.jpg ', ' image/asus_f3.jpg ', ' image/asus_f4.jpg ', '2018-04-18', 'Asus', 'F510UA FHD ', ' Powerful 8th Generation Intel Core i5-8250U 1.6GHz (Turbo up to 3.4GHz) processor14.2\" wide, 0.8\" thin and portable footprint with 0.3\" NanoEdge bezel for a stunning 80% screen-to-body ratio15.6\" anti-glare Full HD display with ASUS Splendid software enhancement8GB DDR4 RAM and 1TB HDD; Ergonomic chiclet keyboard with fingerprint sensor.Operating System:Windows 10 Pro,Windows 10 HomeComprehensive connections including USB 3.1 Type-C (Gen1), USB 3.0, USB 2.0, and HDMI; Lightning-fast 802.11ac Wi-Fi keeps you connected through any congestion or interferenceNOTE: Refer the User Manual before useScreen Size15.6 inchesMax Screen Resolution1920x1080 pixelsProcessor1.6 GHz Intel Core i5RAM8 GB DDR4Hard Drive1000 GB Mechanical Hard DriveCard DescriptionIntegratedWireless Type802.11 A/CNumber of USB 2.0 Ports2Number of USB 3.0 Ports1'),
(95, 'Lenovo Ideapad 210s 11.6 inch HD Flagship Laptop ', 'Laptop', 13121, 31, 'image/lenovo1.jpg ', ' image/lenovo2.jpg ', ' image/lenovo3.jpg ', ' image/lenovo4.jpg ', '2018-04-26', 'Lenovo', 'Ideapad 210s ', ' 11.6\" (1366 x 768) HD Energy-efficient LED backlight display, Intel HD Graphics 500Intel Celeron N3350 Dual-Core processor, 1.10 GHz Base up to 2.0 GHz, 2GB RAM, 32GB eMMCStereo Speakers, 802.11ac, Bluetooth 4.0, Webcam, Media Reader1 x Headphone output/Microphone input combo, 1 x USB Type-C, 2 x USB 3.0, 1 x HDMIColor: Mineral Gray, Windows 10, 0.7\" Thin, 2.54lbs Weight, Battery: 2-cell lithium-ion, 1-year Microsoft Office 365 Personal'),
(96, 'Samsung Chromebook (Wi-Fi, 11.6-Inch) ', 'Laptop', 12911, 26, 'image/sam_ch1.jpg ', ' image/sam_ch2.jpg ', ' image/sam_ch3.jpg ', ' image/sam_ch4.jpg ', '2018-04-30', 'Samsung', 'Chrome fr12 ', ' This Certified Refurbished product is certified factory refurbished, shows limited or no wear, and includes all original accessories plus a 90-day warrantyChrome OS, Samsung Exynos 5250 Dual Core ProcessorDisplay: 11.6\" LED HD 1366 x 768 16:9, Ports: HDMI, Headphone/MIC combo, 1 x USB 3.0   1 x USB 2.0, 3- in-1 (SD/SDHC/SDXC)Memory: 2 GB DDR3L RAM, 16GB Solid State DriveBuilt-in dual band Wi-Fi 802.11 a/b/g/n, Webcam, 3W Stereo Speaker'),
(97, 'HP EliteBook 840 G2 14\" HD Laptop Computer ', 'Laptop', 13112, 12, 'image/hp_elite1.jpg ', ' image/hp_elite2.jpg ', ' image/hp_elite3.jpg ', ' image/hp_elite4.jpg ', '2018-04-02', 'Hp', 'EliteBook 840 G2 ', ' This Certified Refurbished product is tested and certified to look and work like new. The refurbishing process includes functionality testing, basic cleaning, inspection, and repackaging. The product ships with all relevant accessories, a minimum 90-day warranty, and may arrive in a generic box. Only select sellers who maintain a high performance bar may offer Certified Refurbished products on Amazon.com14 \" HD SVA anti-glare LED (1366 x 768), Intel HD Graphics 5500Intel Core i5-5200U Processor 2.20GHz(2 cores, 3M Cache, up to 2.70GHz); 8GB (1 x 8GB) DDR3L SDRAM, 500GB HDD802.11a/b/g/n, Bluetooth 4.0, webcamWindows 10 ProfessionalScreen Size14 inchesScreen Resolution1366 x 768Max Screen Resolution1366 x 768Processor2.2 GHz Intel Core i5RAM8 GB DDR3 SDRAMHard Drive500 GB HDDGraphics Coprocessorintegrated_graphicsChipset BrandintelCard DescriptionintegratedWireless Type802.11abg, 802.11 a/b/g/n, 802.11A'),
(98, 'ASUS Chromebook C202SA-YS02 11.6 ', 'Laptop', 20121, 12, 'image/asus_cs1.jpg ', ' image/asus_cs2.jpg ', ' image/asus_cs3.jpg ', ' image/asus_cs4.jpg ', '2018-04-18', 'Asus', 'C202SA-YS02 11.6 ', ' Intel Celeron N3060 Processor (2M Cache, up to 2.48 GHz)Designed for rugged use with reinforced rubber guards, easy grip handles, and a spill resistant keyboardCan open/edit MS Office files using free embedded QuickOffice editor or Google Docs, and can download Microsoft Office Online (an online version of Microsoft Office) for free. Cannot install standard MS Office software.4 GB DDR3 RAM; 16GB Flash Storage; No CD or DVD drive11.6 inches HD 1366x768 Anti-Glare Display, up to 10 hours of battery lifeScreen Size11.6 inchesMax Screen Resolution1366*768 pixelsProcessor1.6 GHz Intel CeleronRAM4 GB DDR3LHard Drive16 GB emmcGraphics CoprocessorIntel HD GraphicsCard DescriptionintegratedWireless Type802.11 A/CNumber of USB 3.0 Ports2Average Battery Life (in hours)10 hours'),
(99, 'Acer Flagship CB3-532 15.6 ', 'Laptop', 30111, 8, 'image/asus_cbr1.jpg ', ' image/asus_cbr2.jpg ', ' image/asus_cbr3.jpg ', ' image/asus_cbr4.jpg ', '2018-04-09', 'Acer', 'CB3-532 15.6 ', ' This Certified Refurbished product is tested and certified to look and work like new. The refurbishing process includes functionality testing, basic cleaning, inspection, and repackaging. The product ships with all relevant accessories, a minimum 90-day warranty, and may arrive in a generic box. Only select sellers who maintain a high performance bar may offer Certified Refurbished products on Amazon.com15.6\" Anti-Glare HD WLED Backlight Display 1366x 768 with Acer ComfyView Technology; HD WebcamIntel Celeron Dual Core N3060 1.6GHz boost up to 2.48GHz; 2GB DDR3 RAM, 16GB Flash SSDIntel Dual Band Wireless-AC 7265; Bluetooth 4.0; 2 x USB 3.0; HDMI; Intel HD Graphics 400Google Chrome OS; 3-cell Lithium Polymer up to 7hr battery life; 4.3 lbsKey Specifications and Features:Operating System: Chrome OSScreen: 15.6\" HD WLED backlight Display Acer ComfyView TechnologyProcessor: Intel Celeron Dual Core Processor N3060 1.6GHz up to 2.48GHz Turbo FrequencyMemory: 2 GB LPDDR3Storage: 16 GB Flash SSDGraphics Card: Intel HD Graphics 400Bluetooth: YesPorts:2 x USB 3.01 x HDMIPower:45-watt AC adapter3-cell Lithium Polymer'),
(100, 'Acer Chromebook CB3-131-C3SZ 11.6-Inch Laptop ', 'Laptop', 321111, 12, 'image/acer_cb1.jpg ', ' image/acer_cb2.jpg ', ' image/acer_cb3.jpg ', ' image/acer_cb4.jpg ', '2018-05-03', 'Acer', 'CB3-131-C3SZ ', ' This Certified Refurbished product is certified factory refurbished, shows limited or no wear, and includes all original accessories plus a 90-day warranty.Intel Celeron N2840 2.16 GHz, 1MB L2 Cache; 2 GB DDR3L SDRAM; 16GB Solid State DiskBluetooth 4.0, Built-In HD Webcam, 1 - USB 3.0 Port, 1-USB 2.0 Port, 1 - HDMI Port11.6\" HD ComfyViewTM Widescreen IPS LED-backlit Display, Intel HD GraphicsPatterned Aluminum Cover, Google Chrome, Up to 9-hour battery lifeScreen Size11.6 inchesScreen Resolution1366x768Max Screen Resolution1366 x 768Processor2.16 GHz Celeron N2840RAM2 GB DDR3 SDRAMHard Drive16 GB SSDGraphics CoprocessorIntel HD GraphicsChipset BrandintelCard DescriptionintegratedWireless Type802.11abgNumber of USB 2.0 Ports1Average Battery Life (in hours)9 hours'),
(101, 'Lenovo Thinkpad T430 Built Business Laptop ', 'Laptop', 12000, 61, 'image/lenovo_t1.jpg ', ' image/lenovo_t2.jpg ', ' image/lenovo_t3.jpg ', ' image/lenovo_t4.jpg ', '2018-04-19', 'Lenovo', 'T430 Built Business  ', ' This Certified Refurbish product is tested and certified to look and work like new. The refurbishing process includes functionality testing, basic cleaning, inspection, and repackaging.Intel Dual Core i5 2.6 to 3.3 Ghz Processor, 8GB Memory, 320GB SATA HDD.Webcam, DVD.This product will arrive upgraded to Windows 10 proScreen Size14 inchesProcessor2.6 GHz Intel Core i5RAM8 GB SDRAM DDR3Hard Drive320 GB HDD 5400 rpmGraphics Coprocessorintegrated_graphicsChipset BrandintelWireless Type802.11bgn'),
(102, 'Huawei Honor 6X Dual Camera ', 'Mobile Phone', 10000, 11, 'image/6x1.jpg ', ' image/6x2.jpg ', ' image/6x3.jpg ', ' image/6x4.jpg ', '2018-04-18', 'Huawei', ' Honor 6X ', ' The dual-lens 12MP   2MP rear Camera captures colorful HD photos day or night and Features an ultra-fast focus time of 0.3 Seconds.When two SIM cards are inserted, only one SIM card can be set as the 4G/3G/2G SIM. The other SIM card slot only supports 2G networks.An Octa-Core processor(16nm) and 3GB RAM, Plus the smart file system allows for gaming, browsing, listening to music or running multiple apps at the same time.Wide Aperture range (F/0.95-Back for/16) allows for a professional-grade shallow depth of field blurred background effect.The Honor 6x battery delivers a delightful 2.15 days of usage, and 1.5 days of very heavy usage, on a full charge.Dual card dual standby single pass:supports only dual card dual standbysingle pass, which means you cannot use both SIMcards for calls or data services simultaneously'),
(104, 'BLU R1 HD Cell Phone 16GB - Black  ', 'Mobile Phone ', 13122, 99, 'image/blu1.PNG ', 'image/blu2.PNG ', 'image/blu3.PNG ', 'image/blu4.PNG ', '2018-04-12', 'BLU', 'BLU ', ' Fast 1.3 GHz quad-core MediaTek 6735 ARM Cortex processor with 16 GB Internal memory, 2 GB RAM and supports 2.4GHz wifi bandEnjoy the best of Google Android 6.0 Marshmallow, including Google Maps, Gmail, Play Store, and moreDual SIM and MicroSD support for up to 64 GB of expandable storageStunning 5-Inch HD display with curved Gorilla Glass 3 protection, plus an 8 MP main camera and 5 MP selfie camera that includes a front-facing LED flash4G LTE plus GSM unlocked for your favorite compatible carrier or for international travel (including AT '),
(105, 'Samsung Galaxy Core Prime G360T 4G LTE  ', 'Mobile Phone', 4150, 13, 'image/sam_p1.jpg ', ' image/sam_p2.jpg ', ' image/sam_p3.jpg ', ' image/sam_p4.jpg ', '2018-04-18', 'Samsung', ' Prime G360t ', ' Display: 4.5-inchesCamera: 5-MPProcessor Speed: 1.2 GHzThe product ships with all relevant accessoriesFor use with T-Mobile ONLY'),
(106, 'Samsung Galaxy J7 Perx ', 'Mobile Phone', 6000, 91, 'image/sam_j71.jpg ', ' image/sam_j72.jpg ', ' image/sam_j73.jpg ', ' image/sam_j74.jpg ', '2018-05-17', 'Samsung', ' J7 Perx ', ' Boost Mobile ServiceAndroidâ„¢ 7.0, Nougat5.5\" HD Touchscreen2.2GHz Octa-Core Processor16GB ROM and 2GB RAM'),
(107, 'Xiaomi Redmi Note 4 ', 'Mobile Phone', 3000, 91, 'image/xiaomi1.jpg ', ' image/xiaomi2.jpg ', ' image/xiaomi3.jpg ', ' image/xiaomi4.jpg ', '2018-04-26', 'Xiaomi', ' Note4 ', ' Global Model, Dual SIM, Screen: 5.5 inches 1080 x 1920 pixels (~401 ppi pixel density) IPS LCD capacitive touchscreen, 16M colors - Octa-core - Fingerprint (rear-mounted), Memory: 32 GB ROM , 3 GB RAM - microSD, up to 256 GB (uses SIM 2 slot) - 4G LTE - Metal Body, 13 MP, f/2.0, phase detection autofocus, dual-LED - Video:1080p@30fps, 720p@120fps, Sensors: Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass.Unlocked cell phones are compatible with GSM carriers such as AT'),
(108, 'LeEco | Le S3 Unlocked Dual-SIM Smartphone ', 'Mobile Phone', 7122, 62, 'image/le1.jpg ', ' image/le2.jpg ', ' image/le3.jpg ', ' image/le4.jpg ', '2018-04-25', 'LeEco', ' Le S3 ', ' From fast processing to a generous 5.5 inch display and award-winning CDLA audio, your Le S3 is built to deliver the ultimate mobile entertainment experienceBest-in-class performance that combines the power of Qualcomm Snapdragon 652 processor, Adreno 510 GPU and X8 LTE connectivity with 3GB memory and 32GB on-board storageGallery-grade photos with 16MP main and 8MP selfie cameras, stunning 4K or slo-mo videos; an intelligent fingerprint scanner that doubles as a camera shutter; an amazing audio experience with award winning CDLA technology and Dolby Atmos3000mAh battery with Qualcomm Quick Charge 3.0 delivers one full day of average use on a single charge; 10 hours of streaming video, 21 hours of talk time or 57 hours of music playback per full chargeLe S3 comes unlocked and compatible with most GSM carriers nationwide in the USA; Networks: LTE-A, LTE, HSPA/ , UMTS, WCDMA, EDGE, GSM; LTE Bands: 1-5/7/8/12/17; 3G Bands/WCDMA: 1/2/4/5/8; 2G Bands: 2/3/5/8; NOT compatible with CDMA carriers such as Verizon, Sprint, Boost Mobile and Virgin Mobile; Le S3 is a dual Nano SIM smartphone'),
(109, 'LG Stylo 3 - Prepaid - Carrier Locked ', 'Mobile Phone', 5011, 71, 'image/lgs1.jpg ', ' image/lgs2.jpg ', ' image/lgs3.jpg ', ' image/lgs4.jpg ', '2018-04-26', 'LG', ' Stylo 3 ', ' Boost Mobile ServiceFingerprint Scanner5.7\" HD Display with Embedded Stylus13MP Rear Camera with 5MP Front Facing Camera16GB ROM and 2GB RAM'),
(110, 'Nokia 6 - 32 GB - Unlocked (AT', 'Mobile Phone', 8211, 11, 'image/nokia1.jpg ', ' image/nokia2.jpg ', ' image/nokia3.jpg ', ' image/nokia4.jpg ', '2018-04-26', 'Nokia Mobile', ' Nokia 6 ', ' Pre-installed selection of Amazon apps, including the Amazon Widget, provide Prime members with easy access to daily deals, Prime movies and TV shows, Prime Music, Prime Photos storage, and more with a single sign-on experienceFast 4G LTE speed, 1.4 GHz Qualcomm Snapdragon 430 octa-core processor, 3 GB of RAM, and 32 GB of internal memory with the option to add up to 128 GB of microSD expandable memoryBrilliant 5.5â€ 2.5D full HD display and a Smart Amplifier with 7.2W peak output and Dolby Atmos16 MP rear-facing and 8 MP front-facing camera with dual-tone flashBuilt-in fingerprint sensor grants you exclusive access to your deviceEnjoy the best of Android 8.0 OreoUnlocked for the freedom to choose your carrier. Compatible with AT'),
(111, 'ALCATEL OneTouch Idol 3 Global Unlocked ', 'Mobile Phone', 4420, 31, 'image/alcatel1.jpg ', ' image/alcatel2.jpg ', ' image/alcatel3.jpg ', ' image/alcatel4.jpg ', '2018-04-24', 'Alcatel', ' Idol3 ', ' Featuring Award-Winning JBL Audio by Harman IDOLâ„¢ 3 brings an amazing on-the-go music experience! With dual front-facing JBL stereo speakers IDOLâ„¢ 3 packs professional audio quality to the palm of your hand for true-to-life sound.IDOLâ„¢ 3 has been specially tuned for leading color and image innovation through Technicolorâ„¢ Color Enhance technology giving the IDOLâ„¢ 3 a vivid cinematic color experience right in the palm of your hand.Pocket Perfect Form Factor: The IDOLâ„¢ 3 (4.7) is designed to be slim and compact for a first class user experience .Android 5.0 LollipopPowered by an Quad-Core QualcommÂ® Snapdragonâ„¢ 410 processor the IDOLâ„¢ 3 delivers ultra-fast 4G LTE connectivity to help keep up with your fast paced life. Get lost in stunning HD video and console-quality gaming.Break free of carrier contracts with the award-winning IDOLâ„¢ 3. Recognized for delivering a high-quality crisp viewing experience slim elegant design and unique features like a fully reversible user-interface the IDOL â„¢ 3 has all the features.Model 6039S-2AALUS7; compatible with Micro SIM Cards'),
(112, 'Simple Mobile Samsung Galaxy J3 Luna Pro ', 'Mobile Phone', 4200, 11, 'image/samj31.jpg ', ' image/samj32.jpg ', ' image/samj33.jpg ', ' image/samj34.jpg ', '2018-04-23', 'Samsung', ' J3 Luna Pro ', ' 5.0\" HD screen; 1.4 GHz quad-core processor; Android 6.0 Marshmallow; 5 MP Camera/2 MP front facing Camera4G LTE; Wi-Fi capable; Bluetooth 4.2 wireless technology; MP3 Player; Internal memory 16 GBFree $50 airtime bundle included. Promotional package includes unlimited Talk, text, data with 30 days of service. Video typically streams at DVD qualityStream on. (Unlimited Netflix, Spotify, Hulu, TV streaming. Subscription required for streaming services.) $50 for truly unlimited Talk, text, '),
(113, 'BLU VIVO X â€“ 6.0 ', 'Mobile Phone', 7000, 12, 'image/blux.jpg ', ' image/blux1.jpg ', ' image/blux3.jpg ', ' image/blux4.jpg ', '2018-04-19', 'BLU', ' x- 6.0 ', ' 6.0 HD  18:9 Widescreen with Corning Gorilla Glass 3 Curved DisplayAdvance Quad cameras: Dual rear cameras - 13MP   5MP with flash, Dual front selfie Camera - 20MP Sony IMX376  8MP 120 degree wide angle with flash64GB Internal memory 4GB RAM Micro SD up to 64GB; Mediatek Helio P25 2.6GHz Octa core processor4,010mAh Battery with 5V/2A Quick Charger and Fingerprint Sensor4G LTE, (1/2/3/4/5/7/8/12/17/28), 3G HSPA  (850/900/1700/1900/2100): US compatibility Nationwide on all GSM Networks including AT'),
(114, 'TENVIS HD IP Camera ', 'Security Camera', 1950, 21, 'image/tenvis1.jpg ', ' image/tenvis2.jpg ', ' image/tenvis3.jpg ', ' image/tenvis4.jpg ', '2018-05-01', 'Tenvis', ' Tenvis 12cs ', ' NIGHT VISION WITH LARGE RANGE! With the core technology \"Smart Eyes\", this HD IP camera provides a clear night vision through infrared red light! The 32FT night vision range helps protecting your home from theft, burglaries, and vandalism.SHOWS EVERY DETAIL IN BRILLIANT CLARITY! 1280*720 Mega Pixels and high-tech optic lens present sharper images. Motion activated camera with real time video is expert in capturing moving objects. So just enjoy fluent and clearest video images!SMART ALARM AND TWO-WAY AUDIO FOR REAL TIME COMMUNICATING! With the function of motion detection, every potential risk will be identified accurately and sent to you immediately. You can also talk to others anytime anywhere through this IP Camera!STABLE AND SMART CONNECTION TO WI-FI! With the technology of â€œSound Wave Smart Connectionâ€ you can finish the Wi-Fi configuration in just one click! Besides, you can also start and stop recording videos through your cell phone with stable network.OUTSTANDING QUALITY! Latest TENVIS camera technology and top-quality standard for video mark this wireless IP camera as an ideal and distinctive solution for many occasions! Plus, FREE REPLACEMENT POLICY and MONEY BACK GUARANTEE make no risk for you!'),
(115, 'Zmodo Wireless Two-Way Audio ', 'Security Camera', 2300, 13, 'image/zmodo1.jpg ', ' image/zmodo2.jpg ', ' image/zmodo3.jpg ', ' image/zmodo4.jpg ', '2018-04-24', 'Zmodo', ' Zmodo Cam 12sd1 ', ' ã€Zmodo Cloud Serviceã€‘: All users are eligible for a 1-month free cloud of our 7 day cloud recording plan. Cloud Service requires no subscription and no credit card credentials. With the plan, you can review, save, and share footage at any time, and reduce false alerts with cloud intelligence.Easy and Quick Setup - Turn on the camera and complete the network configuration in just minutes. Connectivity:IP/Network-2.4GHz Wireless (Incompatible with 5GHz). With a 115Â° field of view, you can use one camera to capture an entire room without ever having to pan or tilt. 3 Year Manufacturer Warranty, including 60-day return for refund Warranty. Lifetime US-based Support.Two-way audio - The camera has a built-in mic so that you can talk and listen through the Zmodo app anywhere and anytime, making it feel like you never left home. IR Night Vision- See what\'s happening in low light conditions with black and white automatic infrared lights. The night vision is adjustable so that you can also see color image in low-light situation.Receive motion alerts - This WiFi camera will send push notification alerts to your smartphone when motion is detected so you will know whatâ€™s happening immediately. You can also playback motion alert video clips to check for missed moments.Full 720p HD video - you can see crystal clear footage of your home with this high-resolution Mini WiFi camera. Always stay connected to your home by remote monitoring through the mobile Zmodo app for iOS and Android or via Internet browser on user.zmodo.com.'),
(116, 'Lensoul 1080P HD Security Camera ', 'Security Camera', 1200, 13, 'image/lensoul1.jpg ', ' image/lensoul2.jpg ', ' image/lensoul3.jpg ', ' image/lensoul4.jpg ', '2018-04-24', 'Lensoul', ' Lensoul cam 42cs ', ' ã€Clear Imageã€‘-Full 1920 x 1080P high-definition with image rectification, 180Â°panoramic advanced six layer glass fish-eye lens combined with manual rotation. Advanced IR night vision up to 30 feet in pitch dark with no light pollution, so your baby or pet will not be disturbed by LED glare.ã€Two-Way Duplex Audioã€‘-Responsive and advanced microphone with a built-in anti-noise filter for a clear 2-way Duplex Audio experience. Intercom Mode: one party to talk and listen at a time or Hands-free Mode: both parties talk and listen freely for maximum flexibility.ã€Motion Detection '),
(117, 'APEMAN WiFi IP Camera 720P Wireless  ', 'Security Camera', 2110, 12, 'image/ape1.jpg ', ' image/ape2.jpg ', ' image/ape3.jpg ', ' image/ape4.jpg ', '2018-04-10', 'Apeman', ' Apeman 90kl1 ', ' ã€Reliable Remote Controlling Technologyã€‘Keep an eye on your home, families and stuff when you are far away from home. Perfect choice for home/office security, children/pet care. With more servers set and improved, you can have a smooth access to live view using phone data or other Wi-Fi when you are out.ã€Quick '),
(118, 'YI 1080p Home Camera ', 'Security Camera', 2133, 12, 'image/YI.jpg ', ' image/YI2.jpg ', ' image/YI3.jpg ', ' image/YI4.jpg ', '2018-04-17', 'YI', ' YI 1080P 67WE ', ' 24/7 Full HD Recording - F/2.0 aperture, 122 wide-angle lens, 1080p/15fps to capture moments with clear picture. Features two-way audio to allow you to receive and transmit audio from any location with a WiFi connection.Enhanced Night Vision - 8 individual 940nm infrared LED\'s, which automatically turns on infrared (IR) in low light conditions, allowing you to see clearly in the dark.Activity Alerts - Baby Crying Detection and Motion Detection features use state-of-the-art technology to detect and send notifications to your phone. Activity Alerts (7-day storage in YI Cloud) available free of charge without a microSD memory card or a YI Cloud subscription.YI Home App - Acess your camera with our mobile APP anytime and anywhere. Allows sharing your camera with up to 5 family members or friends, and view multiple cameras on a single account.Cloud Storage - Supports YI Cloud to avoid the risk of losing footage from a microSD memory card, and ensures all recorded video is safe, secure, and protected with the most efficient compression and highest protection of data. Local backup supports up to 32GB Class10 microSD cards with FAT32 format.'),
(119, 'Wansview Wireless 1080P IP Camera ', 'Security Camera', 4321, 34, 'image/wansview1.jpg ', ' image/wansview2.jpg ', ' image/wansview3.jpg ', ' image/wansview4.jpg ', '2018-04-17', 'Wansview', ' Wansview NO91q ', ' FULL 1080P HD VIDEO CAMERA: Wansview full HD home camera with 1920*1080P resolution at 25fps,the living stream can be accessed via iOS/Android mobile Phone, Windows PC and Apple Mac Software and http web browsers, you may use it as a baby monitor to view your baby even you are outside home.Reliable2.4G WiFi CONNECTION: Quick WiFi setup via mobile App â€œWansviewâ€ on iPhone or Android smartphone. Wireless security camera supports remote access via mobile App anywhere and anytime. This security camera with Micro SD card slot (max 128GB supported), the videos can be saved and playbacked on Windows and Mac laptop without taking it out of camera. Support Windows and Mac 7/24 videorecording, if camera be stolen, you can check your local computer to see what happened.SMART PAN/TILT/ZOOM CAMERA: This wifi ip camera provides wider viewing angle with horizontal 350 degree(pan) and vertical 76 degree (tilt) with 4x digital zoom function for complete coverage of your home. There is 8 presets which can be adjusted to some places and zoom to make it bigger to see.CLEAR TWO-WAY AUDIO'),
(120, 'ZOSI HD 800TVL 24PCS IR-LEDs 3.6mm lens    ', 'Security Camera ', 2121, 12, 'image/zoshi1.jpg ', 'image/zoshi2.jpg ', 'image/zoshi3.jpg ', 'image/zoshi4.jpg ', '2018-04-24', 'Zosi', 'Zosi ', ' Outdoor / Indoor Day and Night Waterproof IR Bullet Camera24pcs IR LEDs, IR 65ft/20m night vision,800TVL ,3.6mm lensBNC Connector Plugs Into Any DVR,TV or Security Monitor3-Axis Camera Stand,cable through bracket,Aluminum camera housingPlease noted: this camera did not come with power supply    '),
(121, 'Wansview Wireless IP Camera Surveillance ', 'Security Camera', 2130, 91, 'image/wansviewq1.jpg ', ' image/wansviewq2.jpg ', ' image/wansviewq3.jpg ', ' image/wansviewq4.jpg ', '2018-04-25', 'WansView', ' WansView GF6 ', ' MINI HOME CAMERA: Wansview WiFi camera is Super slim(lengh:60mm wide:60mm) but comes with 8 feet power cord far enough to reach faraway power socket( NO BATTERY inside need direct power supply). Easily mount on your wall, ceilling or table, it is a perfect and delicate indoor camera to monitor your baby, elder, pets, babysitter and employees with a 720p high definition video stream. NOTE: NO MICRO SD CARD SLOT. Need a camera with SD Card slot, refer to https://www.amazon.com/dp/B075KGNB58RELIABLE 2.4G WiFi CAMERA :Using â€œAdd Camera Via Wi-Fi modeâ€ via Wansview App on your mobile phone and follow instructions step by step, no complicated setting needed of this wireless surveillance camera.Important tips before connection:IP/Network-2.4GHz Wireless(Incompatible with 5GHz). If your router supports both band, make sure your mobile phone is connected with the 2.4G wifi.WIDER VISION '),
(122, 'Amcrest ProHD 1080P WiFi Camera 2MP ', 'Security Camera', 2311, 12, 'image/amcrest1.jpg ', ' image/amcrest2.jpg ', ' image/amcrest3.jpg ', ' image/amcrest4.jpg ', '2018-04-17', 'Amcrest', ' Amcrest E5TS ', ' EXPERIENCE FULL HD - Observe high-quality footage with the latest Sony image sensor, Ambarella chipset and superior HD 1080p with this wireless camera. A wide 90Â° angle allows you to see more detail and cover more ground to keep more of what you love safe.SMARTER, SAFER SECURITY - Receive intelligent alerts from your security camera to your PC or smartphone via the Amcrest View app. Record events as soon as they happen and store them on a NVR, Synology, QNAP, NAS, FTP, Blue Iris or Amcrest Cloud.ALWAYS RESILIENT - This IP camera offers remote pan/tilt with intelligent digital zoom to help you get an even closer look With IR LED night-vision up to 32 feet, you can keep the people and places you love safe 24/7.FIND SOLACE IN THE CLOUD - Amcrest Cloud was created to ensure that you donâ€™t miss a thing, no matter where you are. With an intuitive interface, you are able to live-stream your footage which enables you to play it back based on your preferences.SIMPLE. RELIABLE. SECURE. - At Amcrest, we want to ensure the safety of our customers, their loved ones, homes, and businesses. Youâ€™ll receive a full 1-year US Warranty and Lifetime Support provided directly from Amcrest.'),
(123, 'YI Home Camera, Wi-Fi IP Indoor  ', 'Camera', 2312, 17, 'image/yihome1.jpg ', 'image/yihome2.jpg', 'image/yihome3.jpg ', 'image/yihome4.jpg', '2018-04-25', 'YI', 'YI ', '  Records in 720p HD to capture clear images for your records and while using 2-way audio (built-in microphone and speaker). 720P/20FPS,700Kbps; 360P/20FPS,200Kbps.111Â° wide-angle lens, 940nm infrared non-invasive sensor, 4x digital zoom. Capture the scene in clarity with the wide-angle lens and zoom capabilities. The non-invasive sensor will not disturb your sleeping children.Built-in support for 802.11b/g/n 2.4Ghz (5Ghz currently not supported) WIFI band. Reliable Wi-Fi connectivity to access your camera with YI Home App on mobile device, and YI Home App on PC at anytime, anywhere.No monthly subscription fees: Secure your videos on a micro SD card, own your video content and access video history anytime. Supports upto 32GB SD micro SD cards with FAT32 format.Real-time streaming to your phone  '),
(124, 'UOKOO Wireless Security Camera ', 'Security Camera', 2310, 12, 'image/uokoo1.jpg ', ' image/uokoo2.jpg ', ' image/uokoo3.jpg ', ' image/uokoo4.jpg ', '2018-04-30', 'Uokoo', ' Uokoo TYA ', ' âœ” ONE KEY CONFIGURATION: Sonic Recognition Technology featuring One Key WiFi Configuration makes setup so quick and easy. Just plug in the power cable, download the iSmartViewPro App and set it up via your iPhone or Andriod smartphone, remote access to the wireless security camera on iPhone/ iPad/ Android phone/ tablet/ MAC/PC, keep an eye on your loves and belongs anywhere anytime. WATCH THE VIDEO GUIDE: https://www.youtube.com/watch?v=-gyUxBtTuBsâœ” NIGHT VISION AND TWO WAY AUDIO: Night vision up to 16-feet - never miss a moment, day or night, with visibility up to 16 feet in complete darkness. Built-in speaker and microphone, not only can you see what is happening in front of your camera, also you can hear and speak. Tell your dog to get off the couch or tell intruders that the police are on the way.âœ” MOTION DETECTION: Email Alert and Android Phone push , Auto Snapshots, support ONVIF. Motion detection sensibility can be adjusted by yourself, When the camera detected abnormity or alarm is triggered, instant alarm pictures will be sent via email/FTP. You can add a few these cameras on the app, view 4 live streams on the phone app or 64 live streams on PC at the same time.âœ” RENOTE ACCESS AND HD NIGHT VISION 720P VIDEO: Remote access to the camera on Smartphone, Tablet, Mac or Windows PC. Quick WiFi setup via iPhone or Andriod smartphone using iSmartViewPro APP. One Key WI-FI configuration via sound beep, quick and easy installation, With Night Vision. Crystal clear HD 720p video 80Âº wide angle lens, 4x digital zoom HD displays with H.264 compression, 1/4\" CMOS Sensor. Motion detection Email Alert and Andriod Phone push , Auto Snapshots, support ONVIFâœ” EASY INSTALLATION: You can put the Mini Security Camera on desk and adjust the viewing angle to your needs or take the plastic part off and put it on the wall with the included screws. Install the home security camera in baby room, office, kitchen, living room. You can monitor every corner of your house with mini ip camera. If you have any question, please contact us freely via email(info@uokoo.net) or skype(uokooteam)'),
(125, 'Blink XT Outdoor/Indoor Home Security Camera ', 'Security Camera', 3211, 11, 'image/blink1.jpg ', ' image/blink2.jpg ', ' image/blink3.jpg ', ' image/blink4.jpg ', '2018-04-30', 'Blink', ' Blink R21 ', ' WEATHERPROOF FOR OUTDOOR OR INDOOR USE: Place and move your wireless Blink camera anywhere around your home both inside and out. Start off with a small system and expand to up to 10 cameras on one Blink Sync ModuleMOTION DETECTOR:  Built-in motion sensor  alarm, when motion detector is triggered, WIFI cameras will send an alert to your smartphone and record a short clip of the event to the cloudBATTERY POWERED SECURITY SYSTEM: Wireless home camera with 2-year battery life, powered by 2 AA Lithium batteries (included), data is sent from IP cameras over Wi-FiSMART HOME VIDEO SECURITY WITH HD VIDEO: Simple self-install home monitoring in minutes; easy control wireless cameras with the included iOS '),
(126, 'NeuTab 10 inch Android Tablet  ', 'Tablet', 10319, 81, 'image/neutab.jpg ', 'image/neutab1.jpg ', 'image/neutab2.jpg ', 'image/neutab3.jpg ', '2018-04-12', 'NeuTab', 'Neutab ', ' Enhanced performance: Android 7.1 operating system with a stable Quad Core CPU, NeuTab aims at providing an ultimate multimedia user experience to every customers. With the upgraded system and design, it ensures an ultra-smooth high quality tablet.Stay connected: Built-in Bluetooth allows easy pairing with speakers, keyboard, and other Bluetooth-enabled devices which makes your NeuTab K1S tablet powerful multi-media. Built-in Wi-Fi enables you stay connected on the go and fast web browsing.Unlimited entertainment: Enjoy access to an ever-expanding world of music, movies, TV shows, books, Android apps, and games with Google Play. HD high resolution screen offers rich graphics, bright colors, and crisp text.Expanded storage: An 16 GB Nand flash enables you to download thousands of apps from Google Play Store and Micro SD card slot allows adding up to 32GB of extra space to store songs, videos, photos and other files.Worry-Free local customer support: Under unexpected situations, your NeuTab tablets does not function properly or you are not happy with your purchase, we proudly offer 1 year manufacturer defect warranty. Questions and concerns could also be assisted online or over phone, simply contact our local customer service for quick response.Screen Size10.1 inchesScreen Resolution1024x600Processor1.3 GHzRAM1 GB SDRAM DDR3Hard Drive16 GBWireless Type802.11 B/G, 802.11bgn, 802.11BAverage Battery Life (in hours)8 hours '),
(127, 'Samsung Galaxy Tab E 9.6\" ', 'Tablet', 12000, 11, 'image/st1.jpg ', ' image/st2.jpg ', ' image/st3.jpg ', ' image/st4.jpg ', '2018-04-17', 'Samsung', ' Tab e9.6 ', ' 1.5 GB RAM memoryResolution: 800 x 1280 pixels (157 PPI pixel density)Screen Size9.6 inchesScreen Resolution1280 x 800 pixelsMax Screen Resolution1280x800 pixelsProcessor1 GHz Intel AtomRAM16 GB DDR3Hard Drive16 GB Mechanical Hard DriveGraphics Coprocessor16gbCard DescriptionIntegratedWireless TypeBluetoothNumber of USB 2.0 Ports2Number of USB 3.0 Ports3Average Battery Life (in hours)20 hours');
INSERT INTO `product` (`productId`, `productName`, `category`, `price`, `quantity`, `productImage0`, `productImage1`, `productImage2`, `productImage3`, `released`, `brand`, `model`, `productDescription`) VALUES
(128, 'ASUS MeMO Pad 7 ME176CX-A1-WH 7-Inch Tablet ', 'Tablet', 2311, 11, 'image/asus_memo1.jpg ', ' image/asus_memo2.jpg ', ' image/asus_memo3.jpg ', ' image/asus_memo4.jpg ', '2018-04-25', 'Asus', ' memo pad ', ' 1.33 GHz Quad-Core Intel Atom processor, Android 4.4 KitKat16 GB Storage expandable by 64 GB with micro SD, 1 GB RAM7-inch HD IPS DisplayOver $270 worth of content and services includedScreen Size7 inchesMax Screen Resolution1280*800 pixelsProcessor1.33 GHz Intel AtomRAM1 GB DDR3Hard Drive16 GB emmcChipset BrandintelWireless Type802.11bgnNumber of USB 2.0 Ports1Average Battery Life (in hours)9 hours'),
(129, 'Azpen A746 7\" Quad Core  ', 'Tablet', 1121, 81, 'image/azpen1.jpg ', 'image/azpen2.jpg ', 'image/azpen3.jpg ', 'image/azpen4.jpg ', '2018-04-24', 'Azpen', 'A746 ', ' Screen Size7 inchesMax Screen Resolution800 x 480RAM0.5 GBMemory Speed1.3 GHzHard Drive8 GB SSDWireless Type802.11bgnAverage Battery Life (in hours)3.5 hours '),
(130, 'MobileDemand Flex 8A ', 'Tablet', 1278, 10, 'image/mobiled1.jpg ', ' image/mobiled2.jpg ', ' image/mobiled3.jpg ', ' image/mobiled4.jpg ', '2018-04-26', 'MobileDemand Lc', ' Flex 8A ', ' Microsoft Windows 10 Professional with an InteÂ® Quad-Core processor giving you all day productivity.8\" 1280x800 display and 7  hour battery lifeProtective case and screen protector is MIL-STD-810G certified, tested by dropping the tablet 26 times from 5 feet to plywood over concreteEasy to carry and hold with included handle and hand strapVehicle Mount AvailableScreen Size8 inchesScreen Resolution1280 x 800Max Screen Resolution1280 x 800RAM1 GB SDRAM DDR3Hard Drive64 GB eMMCChipset BrandIntelWireless Type802.11abg, 5.8 GHz Radio Frequency, BluetoothNumber of USB 2.0 Ports1Average Battery Life (in hours)5 hours'),
(131, 'Qty: Include Add a Protection Plan: 4-Year Protection for $8.99 3-Year Accident Protection for $6.29 Add to Cart Turn on 1-Click ordering for this browser Deliver to Singapore Add to List Have one to sell? Sell on Amazon               VIDEO  Yuntab Google Android 7 inch Tablet PC Wifi 8GB Ram Z88 Allwinner A33 Quad-core 2200mAh Dual Cameras Pad (Green) Roll over image to zoom in Yuntab Yuntab Google Android ', 'Tablet', 3122, 71, 'image/yuntab1.jpg ', ' image/yuntab2.jpg ', ' image/yuntab3.jpg ', ' image/yuntab4.jpg ', '2018-04-29', 'YunTab', ' Google Tab12 ', ' 7 inch capacitive multi-touch screen with 1024*600 HD Resolution makes everything crisp and sharp. You can read text, see images and watch videos from a wider angle than normal screen. You can surely receive the most fantastic and greatest viewing experience.WIFI for Surf the Internetï¼šSurfing the Internet and learning, easy access, wonderful lifttime.8GB RAM, Expandable by MicroSD to 32GB. With pre-loaded Google Play store, it is accessible to thousands of apps and games.Google Android 4.4 builds on the things people love most about Android and is the most stable operating system. Improved performance over other Android systems increases memory reclaim by 20 %, which means you can switch apps and have better performance on your device.This tablet is equipped with Allwinner A33 Quad Core high-speed processing platform (1.5GHz) and Quad core GPU. It offers ultra-fast online surfing speed. Enhanced with DDR3 memory, all applications like video playing and 3D gaming experience on this tablet run faster than ordinary ones.Screen Size7 inchesRAM512 MBWireless Type802.11 B/G, 802.11bgn, 802.11BAverage Battery Life (in hours)8 hours'),
(132, 'Lenovo Tab 4, 10.1 ', 'Tablet', 1289, 61, 'image/lenovi_tab1.jpg ', ' image/lenovi_tab2.jpg ', ' image/lenovi_tab3.jpg ', ' image/lenovi_tab4.jpg ', '2018-04-18', 'Lenovo', ' Lenovo tab 4 ', ' THEATER-LIKE MULTIMEDIA: 10-inch tablet has a brilliant HD display with booming Dolby Atmos Audio and built-in dual-stereo front-facing speakers perfect for binge-watching TV and movies on-the-goTABLET FOR KIDS: Transform to a kids tablet with Lenovo Kid\'s Pack, including a shock-resistant bumper, blue-light screen filter and fun stickers; family sharing is now a breezeMULTI-ACCOUNT: With multi-user and multi-space functionality, switch to Productivity Mode and add the Lenovo Bluetooth keyboard for a 2-in-1 tabletHIGH PERFORMANCE ANDROID TABLET: Wifi tablet has a 64-bit Quad-core Snapdragon processor of up to 1.4 GHz, 2GB of RAM, plus an epic 20 hour battery life for seamless performance on any day-to-day tasksBOX CONTAINS: Lenovo Tablet Tab 4 10, Charger, Micro USB, Safety/Warranty Guide, Quick-Start Guide; perfect tablet for kids, work or playScreen Size10.1 inchesScreen Resolution1280 x 800Max Screen Resolution1280x800 pixelsProcessor1.4 GHz SnapdragonRAM2 GBHard DriveFlash Memory Solid StateCard DescriptionIntegratedWireless Type802.11B, 802.11G, 802.11n'),
(133, 'RCA Galileo Pro 2 ', 'Tablet', 6112, 61, 'image/rca1.jpg ', ' image/rca2.jpg ', ' image/rca3.jpg ', ' image/rca4.jpg ', '2018-06-14', 'RCA', ' RCA K12 ', ' 11.5\" touchscreen, 1024 x 600 resolution, virtual keyboard with Swype DisplayQuad-Core processor, 1GB DDR, 32GB HDD1 x micro USB 2.0 port, 1 x USB mini HDMI port, 1 x Combo Headphone/Mic Jack, 1 x USB 2.0 port802.11, Bluetooth 4.0, Rear 2MP camera and front 1MP webcam, Built-in speakerAndroid 6.0 OS (Marshmallow), 0.43\" Thin, 1.65lbs Weight, Battery: Up to 6 hours of battery life on a single charge, Color: BlackScreen Size11.5 inchesRAM1 GBHard Drive32 GB'),
(134, 'Samsung Galaxy Tab S3 ', 'Tablet', 6234, 92, 'image/sam_tab1.jpg ', ' image/sam_tab2.jpg ', ' image/sam_tab3.jpg ', ' image/sam_tab4.jpg ', '2018-04-02', 'Samsung', ' Tab S3 ', ' Includes the Samsung S Pen StylusFeaturing High Dynamic Range on a Super AMOLED display, the Galaxy Tab S3 delivers cinematic vividness, detail and deep contrast to a screen that fits in your hands.Our revolutionary S Pen is more precise and pressure-responsive than ever, and never needs to be charged, liberating you to create, translate, and navigate without limits.Powerful Quad speakers, tuned by AKG, calibrate with your movements as you rotate the Galaxy Tab S3, and intuitively reflect whatâ€™s playing on-screen.Easily switch from touch to type with a feather light keyboard* that auto-pairs, attaches on contact and never needs charging (*keyboard sold seperately).'),
(135, 'Lenovo Tab 10 ', 'Tablet', 7811, 91, 'image/ltab1.jpg ', ' image/ltab2.jpg ', ' image/ltab3.jpg ', ' image/ltab4.jpg ', '2018-04-27', 'Lenovo', ' L Tab10 ', ' MULTI-ACCOUNT: Multiuser sharing makes this the ideal family tablet, offering separate personal profiles and app configurations for every user; family sharing is now a breezeTABLET FOR KIDS: The Kid\'s Mode interface lets children have a dedicated profile, while you control usage and limit access to websites and appsTHEATER-LIKE MULTIMEDIA: 10-inch tablet has a brilliant HD display with booming Dolby Atmos Audio and built-in dual speakers, perfect for binge-watching TV and movies on-the-goLONG-LASTING BATTERY: Whether for work or play, this Android tablet has got you covered all day long with an epic 10 hour battery lifeBOX CONTAINS: Lenovo Tab 10, Charger and USB Cable, Safety/Warranty Guide, Quick-Start Guide, Cleaning Cloth; perfect tablet for kids, work or playScreen Size10.1 inchesMax Screen Resolution1280x800 pixelsProcessor1.3 GHz SnapdragonRAM2 GBHard DriveFlash Memory Solid StateCard DescriptionIntegrated'),
(136, 'Samsung Galaxy Tab A 7 ', 'Tablet', 4890, 34, 'image/taba1.jpg ', ' image/taba2.jpg ', ' image/taba3.jpg ', ' image/taba4.jpg ', '2018-05-04', 'Samsung', ' Tab A 7 ', ' Comfortable to the touch and light in your hands, the Tab A 7.0\" is easy to take anywhere.Enjoy more of your favorite music, photos, movies and games on the go with a microSD card1that expands your tabletâ€™s memory from 8GB2 to up to an additional 200GBThe long-lasting battery keeps you powered up to watch, read and game at home or on the gofor up to 11 hours of Internet usage.3Bring engaging educational content to kids of every age when you subscribe to Samsung Kids.Make shareable moments better with advanced camera features. Catch more in each photo withPanorama and Continuous Shot modes.Item Dimensions L x W x H:0.3 x 4.3 x 7.4 inchesScreen Size7 inchesScreen Resolution1280 x 800 pixelsMax Screen Resolution1280 x 800 pixelsProcessor1.3 GHz NoneRAM1.5 GB DDR3Hard Drive8 GBCard DescriptionIntegratedWireless TypeBluetoothAverage Battery Life (in hours)10 hours'),
(137, 'NuVision 8-inch Full HD ', 'Tablet', 3411, 12, 'image/nuViosion1.jpg ', ' image/nuViosion2.jpg ', ' image/nuViosion3.jpg ', ' image/nuViosion4.jpg ', '2018-04-25', 'NuVision', ' NuViosn HN7 ', ' creen Size8 inchesMax Screen Resolution1920 x 1200ProcessorIntel AtomRAM2 GBWireless Type802.11 B/G, 802.11bgn, 802.11BAverage Battery Life (in hours)9 hoursBrand NameNUVISIONItem model numberTM800W610LOperating SystemWindows 10 HomeItem Weight9.6 ouncesProduct Dimensions8.3 x 0.5 x 4.9 inchesItem Dimensions L x W x H8.3 x 0.5 x 4.9 inchesColorsilverRear Webcam Resolution5 MPProcessor BrandintelProcessor Count4Computer Memory TypeDDR DRAMFlash Memory Size32 GBPower SourceBatteryBatteries1 Lithium Polymer batteries required.'),
(138, 'Wensltd Womens Turtleneck Long Sleeve ', 'Women Clothing', 200, 90, 'image/wens1.jpg ', ' image/wens2.jpg ', ' image/wens3.jpg ', ' image/wens4.jpg ', '2018-05-02', 'WensLTD', ' None ', ' Material:Cotton BlendSize:S Bust:96cm/37.8\" Sleeve:71cm/28.0\" Length:65cm/25.6\"Size:M Bust:101cm/39.8\" Sleeve:72cm/28.3\" Length:66cm/26.0\"Size:L Bust:106cm/41.7\" Sleeve:73cm/28.7\" Length:67cm/26.4\"Size:XL Bust:111cm/43.7\" Sleeve:74cm/29.1\" Length:68cm/26.8\"'),
(139, 'MEYKISS Women\'s Loose Batwing-sleeved Fall Clothing Pullover Blouse ', 'Women Clothing', 300, 80, 'image/mey1 - Copy.JPG ', ' image/mey1.JPG ', ' image/mey2 - Copy.JPG ', ' image/mey2.JPG ', '2018-05-02', 'MeyKiss', ' None ', ' Loose cut, leisure feelBreathable and Comfortable:good quality of fabricMaterial: Cotton BlendBatwing-sleeved blousePackage with:1* MEYKISS Brand Women\'s Loose Batwing-sleeved Fall Clothing Pullover Blouse(MEYKISS Tags attached)'),
(140, 'Wensltd Women Hoodies ', 'Women Clothing', 100, 12, 'image/wensltdr1 - Copy (2).jpg ', ' image/wensltdr1 - Copy (3).jpg ', ' image/wensltdr1 - Copy.jpg ', ' image/wensltdr1.jpg ', '2018-04-30', 'Wensltd', ' None ', ' Material:Cotton Blend.Size:S Bust:88cm/34.64\" Shoulder:37cm/14.56\" Sleeve:61cm/24.01\" Length:76cm/29.92\"Size:M Bust:92cm/36.22\" Shoulder:38cm/14.96\" Sleeve:62cm/24.40\" Length:77cm/30.31\"Size:L Bust:96cm/37.79\" Shoulder:39cm/15.35\" Sleeve:63cm/24.80\" Length:78cm/30.70\"Size:XL Bust:100cm/39.37\" Shoulder:40cm/15.74\" Sleeve:64cm/25.19\" Length:79cm/31.10\"'),
(141, 'Wensltd Women Cross Bottom Creative Hooded ', 'Women Clothing', 200, 12, 'image/wens_womens1.jpg ', ' image/wens_womens2.jpg ', ' image/wens_womens3.jpg ', ' image/wens_womens4.jpg ', '2018-04-25', 'WensLTD', ' none ', ' Material:Cotton.Size:S Bust:92cm/36.2\" Sleeve:42cm/16.5\" Length:85cm/33.5\"Size:M Bust:96cm/37.8\" Sleeve:43cm/16.9\" Length:86cm/33.9\"Size:L Bust:100cm/39.4\" Sleeve:44cm/17.3\' Length:87cm/34.3\"Size:XL Bust:104cm/40.9\" Sleeve:45cm/17.7\" Length:88cm/34.7\"'),
(142, 'Lands\' End Women\'s Petite Sport Knit Denim Pants ', 'Women Clothing', 300, 12, 'image/land1 - Copy.JPG ', ' image/land1.JPG ', ' image/land2 - Copy.JPG ', ' image/land2.JPG ', '2018-04-10', 'Land\'s End', ' none ', ' French terry fabric has the look of denimEasy, full-elastic waistSide pockets hold small essentials'),
(143, 'PajamaGram Women\'s Soft Cotton ', 'Women Clothing', 431, 13, 'image/pajam1 - Copy.JPG ', ' image/pajam1.JPG ', ' image/pajam2 - Copy.JPG ', ' image/pajam2.JPG ', '2018-04-23', 'Paja', ' none ', ' 100% CottonA trendy update on the classic nightgown, our Oh-So-Soft Pin Dot Nighty is as soft and comfortable as a baby\'s blanketComfy Relaxed Fit â€“ A-line design, featuring delicate all-over pin dots in white for a sweet, feminine sleepwear optionSupremely Soft â€“ Made from our super-soft 100 percent cotton double brushed jersey material; Finished with white trim for added softness and styleDivine Details â€“ Finished with extra-special designer details, including front-button placket and front pleat for added style'),
(144, 'Gotoly Invisable Strapless Body Shaper ', 'Women Clothing', 531, 12, 'image/gotoloy1.JPG ', ' image/gotoloy2.JPG ', ' image/gotoloy3.JPG ', ' image/gotoloy4.JPG ', '2018-04-26', 'Gotoly', ' none ', ' (Hand Wash, Hang Dry to Maintain Shape '),
(145, 'KISSMODA Women\'s Sexy Fitted Plaid Shirt Long Sleeves  ', 'Women Clothing', 891, 12, 'image/kiss1.jpg ', ' image/kiss2.jpg ', ' image/kiss3.jpg ', ' image/kiss4.jpg ', '2018-04-04', 'Kissmoda', ' none ', ' Attention:\"KISSMODA\" has Registered US Trademark.To ensure quality and size,please choose SOLD BY KISSMODA.This plaid shirt is made of 95% polyester 5% spendex.It is lightweight soft and comfortable against your skin.Machine Wash or Hand Wash Cold with Like Colors,Non Cholrine and Line Dry.Short length style,unique plaid design shirt with long sleeves(non cuffed sleeves),tie front,slim fit,deep V-neck and 2 chest patch Pocket.This sexy blouse is great for women and girls to wear in the occasion of business,date,daily life or travel and in the season of spring,summer fall or winter.Classic plaid shirt especially goes well with skinny jeans or leggings.It is the essential style of your wardrobe.Following are some our customers suggested size for reference:One customer bust is 32A, waist is 24in, hips 34/35, Iâ€™m 5â€™ or 5â€™1 '),
(146, 'icyzone Activewear Running Workouts Clothes ', 'Women Clothing', 981, 78, 'image/icyzone1.jpg ', ' image/icyzone2.jpg ', ' image/icyzone3.jpg ', ' image/icyzone4.jpg ', '2018-04-19', 'icyzone', ' none ', ' âˆš 95% Polyester 5% Spandex. Lightweight, stretchy, moisture-wicking power fabric keep you cool and dryâˆš Machine Washableâˆš Banded crew neckline make sure it\'s stretchy and tag-free neck label offers you the maximum comfortâˆš Racerback style with bound edges and flatlock seamsâˆš Heathered Workout running yoga fitness tank top. Attention! The 3 colors\' combination is pack of 3, but the single color is only oneâˆš Perfect tank top for yoga, exercise, fitness, gym, running, any type of workout or everyday use. icyZone active wear combine fashion, function and performanceâˆš Please enter our store to find the matching part: sports bra, yoga pants, active shorts etc. Amazon Store Link: https://www.amazon.com/icyzone'),
(147, 'Tkria Women Sexy Off Shoulder Floral ', 'Women Clothing', 4511, 90, 'image/tkria1.jpg ', ' image/tkria2.jpg ', ' image/tkria3.jpg ', ' image/tkria4.jpg ', '2018-04-03', 'Tkria', ' none ', ' Materials: Polyester, Spandex.Fashion casual style boho rompers for women for daily life,sexy and charming, making you attractive.Comfortable and soft jumpsuit make you feel cool in the summer,make you look sexy covered.Sexy womens rompers elegant style for daily casual,home,party, club, prom, wedding,office or other occasion.Ideal gift for,Birthday,Valentine\'s Day Christmas , beach vacations, summer beach or any other holiday.This item didn\'t fit on someone with a longer torso.S=5.1-5.6\";107-120bl;M=5.1-5.5\";120-140bl;L=5.2-5.6\";140-160bl;XL=5.3-5.9\";160-170bl;XXL=5.6-5.9\";180bl Please refer to detail dimensions chart in the last picture make sure the item fits before ordering.'),
(148, 'Tkria Women\'s Floral Printed Summer Dress ', 'Women Clothing', 1221, 12, 'image/tk_summer1.jpg ', ' image/tk_summer2.jpg ', ' image/tk_summer3.jpg ', ' image/tk_summer4.jpg ', '2018-04-10', 'Tkria', ' none ', ' Material: drooping silky fabrics breathe freely, and not easy to shrink.Fresh floral print romper, casual, stylish and sexy, 100% summer!!Feature: sleeveless, high neck, halter with tie on back, elastic high waist pleated swing romper. sell as set including crop top and short, two piece outfit for women.Occasion: daily wear, beachwear, vacation, date, party, school, club, at home etc.Available in U.S. standard sizing: S, M, L, XL, ( For More Size Details, Please Check the Size Chart.) 2-7 Days Delivery Via USPS.'),
(149, 'Sherosa Women\'s Casual Color Block Lace ', 'Women Clothing', 761, 11, 'image/she1.jpg ', ' image/she2.jpg ', ' image/she3.jpg ', ' image/she4.jpg ', '2018-04-11', 'Sherosa', ' none ', ' Material: Polyester 85% and Cotton 15%. 100% Brand New,High quality. Soft fabric for comfort,It\'s a little stretchy fabric, light weight, not see throgh, soft touched.Tunic tops; Chic Lace Back design; Striped pattern;Leisure fit top to show your good figurePefect wear with jeans or leggings in spring ,summer,fall or winter !This unique casual loose t-shirt, trendy and elegant item which is suitable for a casual everyday look and any occasions especially for office, parties, clubbing and dating.*Note:Size S-XXL.Plus size fit more people ,Please choose larger size if you like loose fit style,refer to detailed size chart shown \"Product Description\" for your selcetion.Attention:The Shirt has registered Trademark\"Sherosa\",exclusively provided by Sherosa only,and we haven\'t authorized any stores to sell our items. If you find them below our listing, they are all COUNTERFEITER/FORGERY. And our lawyer will take legal action against those behavior!!!'),
(150, 'Steve Madden Women\'s Carrson Dress Sandal ', 'Women Shoes', 1500, 12, 'image/steve.2jpg.jpg ', ' image/steve.4jpg.jpg ', ' image/steve.jpg ', ' image/steve3.jpg ', '2018-04-21', 'Steve Madden', ' none ', ' Suede, leather, or man-made upperImportedSynthetic soleShaft measures approximately 3\" from archHeel measures approximately 4\"Ankle-strap sandal in rich leather featuring covered block heel and single toe strap'),
(151, 'DREAM PAIRS Women\'s Moda Low Heel D\'Orsay Pointed Toe Pump Shoes ', 'Women Shoes', 1220, 67, 'image/dream1.jpg ', ' image/dream2.jpg ', ' image/dream3.jpg ', ' image/dream4.jpg ', '2018-04-18', 'Dream Pairs', ' none ', ' Man Made MaterialHeel measures approximately 3 inches\"Classic Pointed toe '),
(152, 'DREAM PAIRS ARPEL/BERRY Women\'s Formal ', 'Women Shoes', 1312, 12, 'image/dreamp1.jpg ', ' image/dreamp2.jpg ', ' image/dreamp3.jpg ', ' image/dreamp4.jpg ', '2018-04-10', 'Dream Pairs', ' none ', ' SyntheticMan made materialsHeel height: 3.5\" (approx)Platform height 0.25\"(approx)TPR rubber soleSlip-on'),
(153, 'DREAM PAIRS Women\'s Valentine Fashion ', 'Women Shoes', 1322, 12, 'image/dreampa1.jpg ', ' image/dreampa2.jpg ', ' image/dreampa3.jpg ', ' image/dreampa4.jpg ', '2018-03-26', 'Dream Pairs', ' none ', ' Man Made MaterialClassic Peep toe '),
(154, 'Rieker Women\'s Sina 78 Pump ', 'Women Shoes', 3211, 15, 'image/sina1.jpg ', ' image/sina2.jpg ', ' image/sina3.jpg ', ' image/sina4.jpg ', '2018-03-29', 'Sina', ' none ', ' LeatherMade in USA or ImportedSynthetic soleBootie-style pump with woven upper and block heelStretch inset at ankle'),
(155, 'TOETOS Women\'s Cowboy Block Heel Side Zipper Ankle Booties ', 'Women Shoes', 3211, 13, 'image/toetos1.jpg ', ' image/toetos2.jpg ', ' image/toetos3.jpg ', ' image/toetos4.jpg ', '2018-07-19', 'Toetos', ' none ', ' Man Made MaterialClassic clean sleek look in these posh bootiesHeel Height: 1.75\", Platform Measures: 0.2\"(approx)Stylish Low Chunky Stacked HeelShaped with faux leather upper, zipper closure for easy on/offApporx 4\" shaft height'),
(156, 'Premier Standard Women\'s Buckle Strap Block Heel Ankle Booties ', 'Women Shoes', 2131, 17, 'image/p1.jpg ', ' image/p2.jpg ', ' image/p3.jpg ', ' image/p4.jpg ', '2018-04-11', 'Primier Standar ', ' None ', ' 100% VEGAN FABRIC: Eco-friendly and in control. Buy these guilt-free, knowing your purchase is making no dent in the environment!CHUNKY GOODNESS: Feast your eyes on these 3\" ultra chunky heels. These heels are going to make you feel superior with their super chunky look and support. Youâ€™re bound and insured to have the upmost balance with these baddies.rubber soleYou can\'t go wrong with these effortless buckle chunky heel booties! Simple pull on booties are an everyday essential to complete your look. This revolutionary trend has become a wardrobe staple.We love stacked heels to give us a boost in height and these are wearable all day long. Ultra lightweight design featuring an adjustable ankle enclosure for a custom fit.Strike up a conversation with confidence whenever you have on these round toe ankle boots! These ankle boots go with almost any outfit, so pair with confidence!Effortlessly slip these fresh chunky heel booties on and off. A sturdy rubber outsole ensures maximum comfort through prolonged wear. Enjoy a leg lengthening look and pair these with your favorite jeans, shorts, dresses and skirts of any length.Worn year-round, these booties feature a comfortable cushioned insole and a sturdy manmade outsole to provide balance with every step.'),
(157, 'DREAM PAIRS Women\'s Narie-New Suede ', 'Women Shoes', 3211, 12, 'image/dreampai1.jpg ', ' image/dreampai2.jpg ', ' image/dreampai3.jpg ', ' image/dreampai4.jpg ', '2018-04-13', 'Dream Pairs', ' none ', ' man made materialthermoplastic rubber soleHeel measures approximately 2.75 inches\"Rubber TPR outsole, Faux fur liningHeel Height: 2.75\", Platform Measures: 0.2\"(approx)Stylish low wedge heel, round toe and side zipper closureTop opening circumference: 11\" (approx)Padded faux fur lining and cushiones insole for comfort'),
(158, 'ShoBeautiful Women\'s Ankle Boots ', 'Women Shoes', 3211, 14, 'image/sho1.jpg ', ' image/sho2.jpg ', ' image/sho3.jpg ', ' image/sho4.jpg ', '2018-04-10', 'ShoBeautiful', ' none ', ' Synthetic soleHeel measures approximately 3.5 inches\"MEASUREMENTS:Heel Height approximately 3.5\",Platform measures approximately 1.00\"Featuring chunky high heels, almond toe, faux suede upper, lace-up closure, and low platform.These heeled booties don\'t have to feature thick, heavy soles to be comfortable or safe to wear!You\'ll practically live in these stacked heel booties that will match with all your day clothes!The tapered, block heel won\'t have you towering over everyone and will have you walking comfortably for hours!'),
(159, 'Alrisco FH63 Women Faux Suede ', 'Women Shoes', 4112, 5, 'image/alr1.jpg ', ' image/alr2.jpg ', ' image/alr3.jpg ', ' image/alr4.jpg ', '2018-04-13', 'Alrisco', ' none ', ' Material: Faux suede (man-made)Measurement (tested sz 6; approx.): Heel: 3.25\", Shaft (w/ heel): 7.5\", Opening: 10\", True to size, Brand new with original or Alrisco shoe box.Sole / Padding: Treaded non-skid sole / cushioned foot bed with padded insoleCOMFORTABLE AND SECURE FIT: With the perfect amount of padding, you\'ll be able to run around all day with ease in comfort! The construction is designed to give you a secure yet comfortable fit based on the size you choose. Please kindly refer to the size chart prior to selecting.QUALITY AND VALUE: Why spend more on high end seasonal, year-round, occasion styles when you get the same designer quality at discounted and competitive prices? This style can be for just about any outfit with designs to help accentuate your legs and highlight your creative and fashionable look! The treaded outsole will make sure you go about your day and night safely and without fatigue.WORRIED ABOUT OUR ENVORINMENT?: We love animals as much as you do! No animals were hurt during the production of these shoes. They are made with 100% vegan materials from top to sole are all from man made materials. We only work with and carry manufacturers or brands that are very environmentally conscious!'),
(160, 'Sorel Women\'s 1964 Premium Wedge Booties ', 'Women Shoes', 5121, 36, 'image/sorel1 - Copy (2).jpg ', ' image/sorel1 - Copy (3).jpg ', ' image/sorel1 - Copy.jpg ', ' image/sorel1.jpg ', '2018-04-18', 'Srel', ' none ', ' LeatherMade in USA or ImportedSynthetic soleShaft measures approximately 4\" from archPlatform measures approximately 0.75Coated canvas'),
(161, 'L\'Artiste by Spring Step Women\'s Dramatic Boot  ', 'Women Shoes ', 3121, 93, 'image/spring1.jpg ', 'image/spring2.jpg ', 'image/spring3.jpg ', 'image/spring4.jpg ', '2018-04-18', 'Spring', 'none ', ' LeatherImportedSynthetic soleShaft measures approximately 5.5\" from archHeel measures approximately 2.25\"Boot opening measures approximately 10.25\" aroundHand painted leather, pull on bootie with leather floral appliqueInside zipper closureSoft printed textile liningHeel height (approximately): 2 1/2\" stackedHand painting techniques will create color variations (colors may vary) '),
(162, 'DBPOWER EX5000 Action Camera ', 'Camera ', 3122, 81, 'image/dbpower1.jpg ', ' image/dbpower2.jpg ', ' image/dbpower3.jpg ', ' image/dbpower4.jpg ', '2018-04-04', 'DBPOWER', ' EX500 ', ' REAL 1080P 30 FPS FULL-HD SPORTS CAMERA: Capture it all with this pocket-sized portable action camera that offers real 1080P HD 30 fps recording and 14-megapixel photos for awesome image quality. It can also record 720p 30 fps or WVGA or VGA. This camera guarantees you lifelike videos with high detail. Get creative and capture and share your world in high definition anywhere.2-INCH HD LCD DISPLAY '),
(163, 'SAmsung X Camera212 ', 'Camera ', 12311, 9, 'image/dsc1.jpg ', ' image/dsc2.jpg ', ' image/dsc3.jpg ', ' image/dsc4.jpg ', '0001-01-01', 'Samsung', ' x21w ', ' as1212as'),
(166, '121212 ', 'Camera', 121212, 1, 'image/Screenshot (1724).png ', 'image/Screenshot (1725).png', 'image/Screenshot (1726).png ', 'image/Screenshot (1727).png', '0012-12-12', '1212', '1212 ', '12121'),
(165, 'jajajaj ', 'Men Shoes', 71717, 1, 'image/10.jpg ', 'image/11.png', 'image/12.png ', 'image/13.png', '2019-03-26', 'asjsjKS', 'KLSKSK ', 'sdfdsffd');

-- --------------------------------------------------------

--
-- Table structure for table `rate`
--

DROP TABLE IF EXISTS `rate`;
CREATE TABLE IF NOT EXISTS `rate` (
  `rateId` int(11) NOT NULL AUTO_INCREMENT,
  `productRate` int(200) NOT NULL,
  `productIdConnect` int(200) NOT NULL,
  `userIdConnect` int(200) NOT NULL,
  PRIMARY KEY (`rateId`)
) ENGINE=MyISAM AUTO_INCREMENT=25 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `rate`
--

INSERT INTO `rate` (`rateId`, `productRate`, `productIdConnect`, `userIdConnect`) VALUES
(22, 4, 137, 3),
(21, 4, 162, 5),
(20, 3, 162, 2),
(19, 4, 136, 3),
(18, 2, 78, 2),
(17, 3, 139, 2),
(16, 4, 152, 3),
(15, 3, 116, 2),
(14, 4, 127, 3),
(13, 4, 163, 2),
(12, 3, 162, 3),
(23, 2, 163, 3),
(24, 1, 160, 3);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
